framework:
    assets:
        packages:
            cms:
                json_manifest_path: '%kernel.project_dir%/public/build/cms/manifest.json'
            site:
                json_manifest_path: '%kernel.project_dir%/public/build/site/manifest.json'
