framework:
    secret: '%env(APP_SECRET)%'
    error_controller: App\Controller\ErrorController::show
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
